name: firstAction
on: push
env:
  fileName: dragon.txt
jobs:
  first-jop:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
    - name: ExecutingBash
      run: |
        chmod +x bash.sh
        ./bash.sh
    
    - name: arifact upload
      uses: actions/upload-artifact@v7.0.1
      with:
        name: dragon-text-file
        path: $fileName
  
  test-jop2:
    needs: first-jop
    runs-on: ubuntu-latest
    steps:
    - name: arifact Download
      uses: actions/download-artifact@v8.0.1
      with:
        name: dragon-text-file

    - name: dragon file Exists
      run : grep -i "hellodragon" dragon.txt


  test-jop3:
    needs: [first-jop,test-jop2]
    runs-on: ubuntu-latest
    steps:
    - name: arifact Download
      uses: actions/download-artifact@v8.0.1
      with:
        name: dragon-text-file
      
    - name: Read File
      run: cat $fileName
    

    
    